export enum ERROR_CODE {
  // General errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  CANNOT_DELETE = "CANNOT_DELETE",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  FAILED_REQUEST = "FAILED_REQUEST",
  ALREADY_EXISTS = "ALREADY_EXISTS",

  // Authentication errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",

  // Business errors
  BUSINESS_NOT_FOUND = "BUSINESS_NOT_FOUND",
  BUSINESS_ALREADY_EXISTS = "BUSINESS_ALREADY_EXISTS",

  // User errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  CANNOT_DELETE_SELF = "CANNOT_DELETE_SELF",
  CANNOT_DEACTIVATE_SELF = "CANNOT_DEACTIVATE_SELF",

  // Product errors
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS",

  // Supplier errors
  SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND",
  SUPPLIER_ALREADY_EXISTS = "SUPPLIER_ALREADY_EXISTS",

  // Inventory errors
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  INVENTORY_ITEM_NOT_FOUND = "INVENTORY_ITEM_NOT_FOUND",
  INVALID_STOCK_MOVEMENT = "INVALID_STOCK_MOVEMENT",
  STOCK_NOT_FOUND = "STOCK_NOT_FOUND",
  STOCK_ALREADY_EXISTS = "STOCK_ALREADY_EXISTS",
  STOCK_ADJUSTMENT_ERROR = "STOCK_ADJUSTMENT_ERROR",
  STOCK_RESERVATION_FAILED = "STOCK_RESERVATION_FAILED",

  // Transaction errors
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  TRANSACTION_ALREADY_PROCESSED = "TRANSACTION_ALREADY_PROCESSED",
  TRANSACTION_VOIDED = "TRANSACTION_VOIDED",

  // Store errors
  PRODUCT_ALREADY_PUBLISHED = "PRODUCT_ALREADY_PUBLISHED",

  // Database errors
  DATABASE_ERROR = "DATABASE_ERROR",
  QUERY_ERROR = "QUERY_ERROR",
  PARTIAL_SUCCESS = "PARTIAL_SUCCESS",

  // Analytics errors
  BEFORE_BUSINESS_CREATION = "BEFORE_BUSINESS_CREATION",

  // External service errors
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  API_ERROR = "API_ERROR",

  // File errors
  FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",

  // Input errors
  MISSING_INPUT = "MISSING_INPUT",
  INVALID_INPUT = "INVALID_INPUT",
  INPUT_TOO_SHORT = "INPUT_TOO_SHORT",
  INPUT_TOO_LONG = "INPUT_TOO_LONG",

  // Invitation errors
  INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",
  INVITATION_EXPIRED = "INVITATION_EXPIRED",

  // Stripe errors
  STRIPE_ACCOUNT_NOT_CONNECTED = "STRIPE_ACCOUNT_NOT_CONNECTED",
  RECEIVER_STRIPE_ACCOUNT_NOT_CONNECTED = "RECEIVER_STRIPE_ACCOUNT_NOT_CONNECTED",
}

export const ERROR_CODE_STATUS_MAP: Record<ERROR_CODE, number> = {
  [ERROR_CODE.STRIPE_ACCOUNT_NOT_CONNECTED]: 400,
  [ERROR_CODE.RECEIVER_STRIPE_ACCOUNT_NOT_CONNECTED]: 400,
  // General errors
  [ERROR_CODE.INTERNAL_SERVER_ERROR]: 500,
  [ERROR_CODE.BAD_REQUEST]: 400,
  [ERROR_CODE.UNAUTHORIZED]: 401,
  [ERROR_CODE.FORBIDDEN]: 403,
  [ERROR_CODE.CANNOT_DELETE]: 403,
  [ERROR_CODE.NOT_FOUND]: 404,
  [ERROR_CODE.CONFLICT]: 409,
  [ERROR_CODE.VALIDATION_ERROR]: 400,
  [ERROR_CODE.ALREADY_EXISTS]: 409,
  [ERROR_CODE.FAILED_REQUEST]: 500,

  // Authentication errors
  [ERROR_CODE.INVALID_CREDENTIALS]: 401,
  [ERROR_CODE.SESSION_EXPIRED]: 401,
  [ERROR_CODE.ACCOUNT_LOCKED]: 403,

  // Business errors
  [ERROR_CODE.BUSINESS_NOT_FOUND]: 404,
  [ERROR_CODE.BUSINESS_ALREADY_EXISTS]: 409,

  // User errors
  [ERROR_CODE.USER_NOT_FOUND]: 404,
  [ERROR_CODE.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODE.CANNOT_DELETE_SELF]: 409,
  [ERROR_CODE.CANNOT_DEACTIVATE_SELF]: 409,

  // Product errors
  [ERROR_CODE.PRODUCT_NOT_FOUND]: 404,
  [ERROR_CODE.PRODUCT_ALREADY_EXISTS]: 409,

  // Supplier errors
  [ERROR_CODE.SUPPLIER_NOT_FOUND]: 404,
  [ERROR_CODE.SUPPLIER_ALREADY_EXISTS]: 409,

  // Inventory errors
  [ERROR_CODE.INSUFFICIENT_STOCK]: 400,
  [ERROR_CODE.INVENTORY_ITEM_NOT_FOUND]: 404,
  [ERROR_CODE.INVALID_STOCK_MOVEMENT]: 400,
  [ERROR_CODE.STOCK_NOT_FOUND]: 404,
  [ERROR_CODE.STOCK_ALREADY_EXISTS]: 409,
  [ERROR_CODE.STOCK_ADJUSTMENT_ERROR]: 400,
  [ERROR_CODE.STOCK_RESERVATION_FAILED]: 400,

  // Transaction errors
  [ERROR_CODE.TRANSACTION_NOT_FOUND]: 404,
  [ERROR_CODE.TRANSACTION_ALREADY_PROCESSED]: 409,
  [ERROR_CODE.TRANSACTION_VOIDED]: 400,

  // Store errors
  [ERROR_CODE.PRODUCT_ALREADY_PUBLISHED]: 409,

  // Database errors
  [ERROR_CODE.DATABASE_ERROR]: 500,
  [ERROR_CODE.QUERY_ERROR]: 500,
  [ERROR_CODE.PARTIAL_SUCCESS]: 207,

  // Analytics errors
  [ERROR_CODE.BEFORE_BUSINESS_CREATION]: 400,

  // External service errors
  [ERROR_CODE.EXTERNAL_SERVICE_ERROR]: 502,
  [ERROR_CODE.API_ERROR]: 502,

  // File errors
  [ERROR_CODE.FILE_UPLOAD_ERROR]: 500,
  [ERROR_CODE.FILE_NOT_FOUND]: 404,
  [ERROR_CODE.INVALID_FILE_FORMAT]: 400,

  // Input errors
  [ERROR_CODE.MISSING_INPUT]: 400,
  [ERROR_CODE.INVALID_INPUT]: 400,
  [ERROR_CODE.INPUT_TOO_SHORT]: 400,
  [ERROR_CODE.INPUT_TOO_LONG]: 400,

  // Invitation errors
  [ERROR_CODE.INVITATION_NOT_FOUND]: 404,
  [ERROR_CODE.INVITATION_EXPIRED]: 400,
};
