export enum ErrorCode {
  // General errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  CONFLICT = "CONFLICT",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  FAILED_REQUEST = "FAILED_REQUEST",
  ALREADY_EXISTS = "ALREADY_EXISTS",

  // Authentication errors
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  ACCOUNT_LOCKED = "ACCOUNT_LOCKED",

  // Business errors
  BUSINESS_NOT_FOUND = "BUSINESS_NOT_FOUND",
  BUSINESS_ALREADY_EXISTS = "BUSINESS_ALREADY_EXISTS",

  // User errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  CANNOT_DELETE_SELF = "CANNOT_DELETE_SELF",
  CANNOT_DEACTIVATE_SELF = "CANNOT_DEACTIVATE_SELF",

  // Product errors
  PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND",
  PRODUCT_ALREADY_EXISTS = "PRODUCT_ALREADY_EXISTS",

  // Supplier errors
  SUPPLIER_NOT_FOUND = "SUPPLIER_NOT_FOUND",
  SUPPLIER_ALREADY_EXISTS = "SUPPLIER_ALREADY_EXISTS",

  // Inventory errors
  INSUFFICIENT_STOCK = "INSUFFICIENT_STOCK",
  INVENTORY_ITEM_NOT_FOUND = "INVENTORY_ITEM_NOT_FOUND",
  INVALID_STOCK_MOVEMENT = "INVALID_STOCK_MOVEMENT",
  STOCK_NOT_FOUND = "STOCK_NOT_FOUND",
  STOCK_ALREADY_EXISTS = "STOCK_ALREADY_EXISTS",
  STOCK_ADJUSTMENT_ERROR = "STOCK_ADJUSTMENT_ERROR",
  STOCK_RESERVATION_FAILED = "STOCK_RESERVATION_FAILED",

  // Transaction errors
  TRANSACTION_NOT_FOUND = "TRANSACTION_NOT_FOUND",
  TRANSACTION_ALREADY_PROCESSED = "TRANSACTION_ALREADY_PROCESSED",
  TRANSACTION_VOIDED = "TRANSACTION_VOIDED",

  // Database errors
  DATABASE_ERROR = "DATABASE_ERROR",
  QUERY_ERROR = "QUERY_ERROR",

  // External service errors
  EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR",
  API_ERROR = "API_ERROR",

  // File errors
  FILE_UPLOAD_ERROR = "FILE_UPLOAD_ERROR",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",
  INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",

  // Input errors
  MISSING_INPUT = "MISSING_INPUT",
  INVALID_INPUT = "INVALID_INPUT",
  INPUT_TOO_SHORT = "INPUT_TOO_SHORT",
  INPUT_TOO_LONG = "INPUT_TOO_LONG",

  // Invitation errors
  INVITATION_NOT_FOUND = "INVITATION_NOT_FOUND",
  INVITATION_EXPIRED = "INVITATION_EXPIRED",
}

export const ERROR_CODE_STATUS_MAP: Record<ErrorCode, number> = {
  // General errors
  [ErrorCode.INTERNAL_SERVER_ERROR]: 500,
  [ErrorCode.BAD_REQUEST]: 400,
  [ErrorCode.UNAUTHORIZED]: 401,
  [ErrorCode.FORBIDDEN]: 403,
  [ErrorCode.NOT_FOUND]: 404,
  [ErrorCode.CONFLICT]: 409,
  [ErrorCode.VALIDATION_ERROR]: 400,
  [ErrorCode.ALREADY_EXISTS]: 409,
  [ErrorCode.FAILED_REQUEST]: 500,

  // Authentication errors
  [ErrorCode.INVALID_CREDENTIALS]: 401,
  [ErrorCode.SESSION_EXPIRED]: 401,
  [ErrorCode.ACCOUNT_LOCKED]: 403,

  // Business errors
  [ErrorCode.BUSINESS_NOT_FOUND]: 404,
  [ErrorCode.BUSINESS_ALREADY_EXISTS]: 409,

  // User errors
  [ErrorCode.USER_NOT_FOUND]: 404,
  [ErrorCode.USER_ALREADY_EXISTS]: 409,
  [ErrorCode.CANNOT_DELETE_SELF]: 409,
  [ErrorCode.CANNOT_DEACTIVATE_SELF]: 409,

  // Product errors
  [ErrorCode.PRODUCT_NOT_FOUND]: 404,
  [ErrorCode.PRODUCT_ALREADY_EXISTS]: 409,

  // Supplier errors
  [ErrorCode.SUPPLIER_NOT_FOUND]: 404,
  [ErrorCode.SUPPLIER_ALREADY_EXISTS]: 409,

  // Inventory errors
  [ErrorCode.INSUFFICIENT_STOCK]: 400,
  [ErrorCode.INVENTORY_ITEM_NOT_FOUND]: 404,
  [ErrorCode.INVALID_STOCK_MOVEMENT]: 400,
  [ErrorCode.STOCK_NOT_FOUND]: 404,
  [ErrorCode.STOCK_ALREADY_EXISTS]: 409,
  [ErrorCode.STOCK_ADJUSTMENT_ERROR]: 400,
  [ErrorCode.STOCK_RESERVATION_FAILED]: 400,

  // Transaction errors
  [ErrorCode.TRANSACTION_NOT_FOUND]: 404,
  [ErrorCode.TRANSACTION_ALREADY_PROCESSED]: 409,
  [ErrorCode.TRANSACTION_VOIDED]: 400,

  // Database errors
  [ErrorCode.DATABASE_ERROR]: 500,
  [ErrorCode.QUERY_ERROR]: 500,

  // External service errors
  [ErrorCode.EXTERNAL_SERVICE_ERROR]: 502,
  [ErrorCode.API_ERROR]: 502,

  // File errors
  [ErrorCode.FILE_UPLOAD_ERROR]: 500,
  [ErrorCode.FILE_NOT_FOUND]: 404,
  [ErrorCode.INVALID_FILE_FORMAT]: 400,

  // Input errors
  [ErrorCode.MISSING_INPUT]: 400,
  [ErrorCode.INVALID_INPUT]: 400,
  [ErrorCode.INPUT_TOO_SHORT]: 400,
  [ErrorCode.INPUT_TOO_LONG]: 400,

  // Invitation errors
  [ErrorCode.INVITATION_NOT_FOUND]: 404,
  [ErrorCode.INVITATION_EXPIRED]: 400,
};
