export enum PERMISSION {
  // Business permissions
  BUSINESS_VIEW = "business:view",
  BUSINESS_CREATE = "business:create",
  BUSINESS_UPDATE = "business:update",
  BUSINESS_DELETE = "business:delete",

  // Business settings permissions
  BUSINESS_SETTINGS_VIEW = "business_settings:view",
  BUSINESS_SETTINGS_CREATE = "business_settings:create",
  BUSINESS_SETTINGS_UPDATE = "business_settings:update",
  BUSINESS_SETTINGS_DELETE = "business_settings:delete",

  // Product permissions
  PRODUCT_VIEW = "product:view",
  PRODUCT_CREATE = "product:create",
  PRODUCT_UPDATE = "product:update",
  PRODUCT_DELETE = "product:delete",
  PRODUCT_BULK_OPERATIONS = "product:bulk",

  // Inventory permissions
  INVENTORY_VIEW = "inventory:view",
  INVENTORY_UPDATE = "inventory:update",
  INVENTORY_ADJUST = "inventory:adjust",
  INVENTORY_TRANSFER = "inventory:transfer",
  INVENTORY_REPORTS = "inventory:reports",

  // Order permissions
  ORDER_VIEW = "order:view",
  ORDER_CREATE = "order:create",
  ORDER_UPDATE = "order:update",
  ORDER_DELETE = "order:delete",
  ORDER_APPROVE = "order:approve",
  ORDER_FULFILL = "order:fulfill",

  // Purchase Order permissions
  PURCHASE_ORDER_VIEW = "purchase_order:view",
  PURCHASE_ORDER_CREATE = "purchase_order:create",
  PURCHASE_ORDER_UPDATE = "purchase_order:update",
  PURCHASE_ORDER_DELETE = "purchase_order:delete",

  // User management permissions
  USER_VIEW = "user:view",
  USER_CREATE = "user:create",
  USER_UPDATE = "user:update",
  USER_DELETE = "user:delete",
  USER_ASSIGN_ROLES = "user:assign_roles",

  // Warehouse permissions
  WAREHOUSE_VIEW = "warehouse:view",
  WAREHOUSE_CREATE = "warehouse:create",
  WAREHOUSE_UPDATE = "warehouse:update",
  WAREHOUSE_DELETE = "warehouse:delete",

  // Warehouse permissions
  WAREHOUSE_ITEM_VIEW = "warehouse:item:view",
  WAREHOUSE_ITEM_CREATE = "warehouse:item:create",
  WAREHOUSE_ITEM_UPDATE = "warehouse:item:update",
  WAREHOUSE_ITEM_DELETE = "warehouse:item:delete",

  // Category permissions
  CATEGORY_VIEW = "category:view",
  CATEGORY_CREATE = "category:create",
  CATEGORY_UPDATE = "category:update",
  CATEGORY_DELETE = "category:delete",

  // Category permissions
  LOG_VIEW = "log:view",
  LOG_CREATE = "log:create",
  LOG_UPDATE = "log:update",
  LOG_DELETE = "log:delete",

  // Supplier permissions
  SUPPLIER_VIEW = "supplier:view",
  SUPPLIER_CREATE = "supplier:create",
  SUPPLIER_UPDATE = "supplier:update",
  SUPPLIER_DELETE = "supplier:delete",

  // Schedule permissions
  SCHEDULE_VIEW = "schedule:view",
  SCHEDULE_CREATE = "schedule:create",
  SCHEDULE_UPDATE = "schedule:update",
  SCHEDULE_DELETE = "schedule:delete",

  // Invitation permissions
  INVITATION_VIEW = "invitation:view",
  INVITATION_CREATE = "invitation:create",
  INVITATION_UPDATE = "invitation:update",
  INVITATION_DELETE = "invitation:delete",

  // Transaction permissions
  TRANSACTION_PURCHASE_VIEW = "transaction:purchase:view",
  TRANSACTION_PURCHASE_CREATE = "transaction:purchase:create",
  TRANSACTION_PURCHASE_UPDATE = "transaction:purchase:update",
  TRANSACTION_PURCHASE_DELETE = "transaction:purchase:delete",

  TRANSACTION_SALE_VIEW = "transaction:sale:view",
  TRANSACTION_SALE_CREATE = "transaction:sale:create",
  TRANSACTION_SALE_UPDATE = "transaction:sale:update",
  TRANSACTION_SALE_DELETE = "transaction:sale:delete",

  TRANSACTION_DAMAGE_VIEW = "transaction:damage:view",
  TRANSACTION_DAMAGE_CREATE = "transaction:damage:create",
  TRANSACTION_DAMAGE_UPDATE = "transaction:damage:update",
  TRANSACTION_DAMAGE_DELETE = "transaction:damage:delete",

  TRANSACTION_STOCK_ADJUSTMENT_VIEW = "transaction:stock_adjustment:view",
  TRANSACTION_STOCK_ADJUSTMENT_CREATE = "transaction:stock_adjustment:create",
  TRANSACTION_STOCK_ADJUSTMENT_UPDATE = "transaction:stock_adjustment:update",
  TRANSACTION_STOCK_ADJUSTMENT_DELETE = "transaction:stock_adjustment:delete",

  TRANSACTION_TRANSFER_IN_VIEW = "transaction:transfer_in:view",
  TRANSACTION_TRANSFER_IN_CREATE = "transaction:transfer_in:create",
  TRANSACTION_TRANSFER_IN_UPDATE = "transaction:transfer_in:update",
  TRANSACTION_TRANSFER_IN_DELETE = "transaction:transfer_in:delete",

  TRANSACTION_TRANSFER_OUT_VIEW = "transaction:transfer_out:view",
  TRANSACTION_TRANSFER_OUT_CREATE = "transaction:transfer_out:create",
  TRANSACTION_TRANSFER_OUT_UPDATE = "transaction:transfer_out:update",
  TRANSACTION_TRANSFER_OUT_DELETE = "transaction:transfer_out:delete",

  TRANSACTION_RETURN_SALE_VIEW = "transaction:return_sale:view",
  TRANSACTION_RETURN_SALE_CREATE = "transaction:return_sale:create",
  TRANSACTION_RETURN_SALE_UPDATE = "transaction:return_sale:update",
  TRANSACTION_RETURN_SALE_DELETE = "transaction:return_sale:delete",

  TRANSACTION_RETURN_PURCHASE_VIEW = "transaction:return_purchase:view",
  TRANSACTION_RETURN_PURCHASE_CREATE = "transaction:return_purchase:create",
  TRANSACTION_RETURN_PURCHASE_UPDATE = "transaction:return_purchase:update",
  TRANSACTION_RETURN_PURCHASE_DELETE = "transaction:return_purchase:delete",

  TRANSACTION_PRODUCTION_INPUT_VIEW = "transaction:production_input:view",
  TRANSACTION_PRODUCTION_INPUT_CREATE = "transaction:production_input:create",
  TRANSACTION_PRODUCTION_INPUT_UPDATE = "transaction:production_input:update",
  TRANSACTION_PRODUCTION_INPUT_DELETE = "transaction:production_input:delete",

  TRANSACTION_PRODUCTION_OUTPUT_VIEW = "transaction:production_output:view",
  TRANSACTION_PRODUCTION_OUTPUT_CREATE = "transaction:production_output:create",
  TRANSACTION_PRODUCTION_OUTPUT_UPDATE = "transaction:production_output:update",
  TRANSACTION_PRODUCTION_OUTPUT_DELETE = "transaction:production_output:delete",

  // Customer permissions
  CUSTOMER_VIEW = "customer:view",
  CUSTOMER_CREATE = "customer:create",
  CUSTOMER_UPDATE = "customer:update",
  CUSTOMER_DELETE = "customer:delete",

  // Financial permissions
  FINANCIAL_VIEW = "financial:view",
  FINANCIAL_REPORTS = "financial:reports",
  FINANCIAL_EXPORT = "financial:export",

  // System permissions
  SYSTEM_SETTINGS = "system:settings",
  SYSTEM_BACKUP = "system:backup",
  SYSTEM_LOGS = "system:logs",
  SYSTEM_MAINTENANCE = "system:maintenance",

  // Audit permissions
  AUDIT_VIEW = "audit:view",
  AUDIT_EXPORT = "audit:export",

  // Stripe Connect permissions
  STRIPE_CONNECT_MANAGE = "stripe_connect:manage",

  // Inter-Business Payments permissions
  INTER_BUSINESS_PAYMENT_INITIATE = "inter_business_payment:initiate",
  INTER_BUSINESS_PAYMENT_VIEW = "inter_business_payment:view",

  // Notification permissions
  NOTIFICATION_VIEW = "notification:view",
  NOTIFICATION_CREATE = "notification:create",
  NOTIFICATION_UPDATE = "notification:update",
  NOTIFICATION_DELETE = "notification:delete",
}

// Group permissions by feature for easier management
export const PermissionGroups = {
  STRIPE_CONNECT: [PERMISSION.STRIPE_CONNECT_MANAGE],
  INTER_BUSINESS_PAYMENTS: [
    PERMISSION.INTER_BUSINESS_PAYMENT_INITIATE,
    PERMISSION.INTER_BUSINESS_PAYMENT_VIEW,
  ],
  NOTIFICATIONS: [
    PERMISSION.NOTIFICATION_VIEW,
    PERMISSION.NOTIFICATION_CREATE,
    PERMISSION.NOTIFICATION_UPDATE,
    PERMISSION.NOTIFICATION_DELETE,
  ],
  BUSINESS: [
    PERMISSION.BUSINESS_VIEW,
    PERMISSION.BUSINESS_CREATE,
    PERMISSION.BUSINESS_UPDATE,
    PERMISSION.BUSINESS_DELETE,
  ],
  BUSINESS_SETTINGS: [
    PERMISSION.BUSINESS_SETTINGS_VIEW,
    PERMISSION.BUSINESS_SETTINGS_CREATE,
    PERMISSION.BUSINESS_SETTINGS_UPDATE,
    PERMISSION.BUSINESS_SETTINGS_DELETE,
  ],
  PRODUCTS: [
    PERMISSION.PRODUCT_VIEW,
    PERMISSION.PRODUCT_CREATE,
    PERMISSION.PRODUCT_UPDATE,
    PERMISSION.PRODUCT_DELETE,
    PERMISSION.PRODUCT_BULK_OPERATIONS,
  ],
  INVENTORY: [
    PERMISSION.INVENTORY_VIEW,
    PERMISSION.INVENTORY_UPDATE,
    PERMISSION.INVENTORY_ADJUST,
    PERMISSION.INVENTORY_TRANSFER,
    PERMISSION.INVENTORY_REPORTS,
  ],
  ORDERS: [
    PERMISSION.ORDER_VIEW,
    PERMISSION.ORDER_CREATE,
    PERMISSION.ORDER_UPDATE,
    PERMISSION.ORDER_DELETE,
    PERMISSION.ORDER_APPROVE,
    PERMISSION.ORDER_FULFILL,
  ],
  PURCHASE_ORDERS: [
    PERMISSION.PURCHASE_ORDER_VIEW,
    PERMISSION.PURCHASE_ORDER_CREATE,
    PERMISSION.PURCHASE_ORDER_UPDATE,
    PERMISSION.PURCHASE_ORDER_DELETE,
  ],
  USERS: [
    PERMISSION.USER_VIEW,
    PERMISSION.USER_CREATE,
    PERMISSION.USER_UPDATE,
    PERMISSION.USER_DELETE,
    PERMISSION.USER_ASSIGN_ROLES,
  ],
  WAREHOUSES: [
    PERMISSION.WAREHOUSE_VIEW,
    PERMISSION.WAREHOUSE_CREATE,
    PERMISSION.WAREHOUSE_UPDATE,
    PERMISSION.WAREHOUSE_DELETE,
  ],
  WAREHOUSE_ITEMS: [
    PERMISSION.WAREHOUSE_ITEM_VIEW,
    PERMISSION.WAREHOUSE_ITEM_CREATE,
    PERMISSION.WAREHOUSE_ITEM_UPDATE,
    PERMISSION.WAREHOUSE_ITEM_DELETE,
  ],
  CATEGORIES: [
    PERMISSION.CATEGORY_VIEW,
    PERMISSION.CATEGORY_CREATE,
    PERMISSION.CATEGORY_UPDATE,
    PERMISSION.CATEGORY_DELETE,
  ],
  LOGS: [
    PERMISSION.LOG_VIEW,
    PERMISSION.LOG_CREATE,
    PERMISSION.LOG_UPDATE,
    PERMISSION.LOG_DELETE,
  ],
  SUPPLIERS: [
    PERMISSION.SUPPLIER_VIEW,
    PERMISSION.SUPPLIER_CREATE,
    PERMISSION.SUPPLIER_UPDATE,
    PERMISSION.SUPPLIER_DELETE,
  ],
  SCHEDULES: [
    PERMISSION.SCHEDULE_VIEW,
    PERMISSION.SCHEDULE_CREATE,
    PERMISSION.SCHEDULE_UPDATE,
    PERMISSION.SCHEDULE_DELETE,
  ],
  INVITATIONS: [
    PERMISSION.INVITATION_VIEW,
    PERMISSION.INVITATION_CREATE,
    PERMISSION.INVITATION_UPDATE,
    PERMISSION.INVITATION_DELETE,
  ],
  TRANSACTIONS: [
    PERMISSION.TRANSACTION_PURCHASE_VIEW,
    PERMISSION.TRANSACTION_PURCHASE_CREATE,
    PERMISSION.TRANSACTION_PURCHASE_UPDATE,
    PERMISSION.TRANSACTION_PURCHASE_DELETE,
    PERMISSION.TRANSACTION_SALE_VIEW,
    PERMISSION.TRANSACTION_SALE_CREATE,
    PERMISSION.TRANSACTION_SALE_UPDATE,
    PERMISSION.TRANSACTION_SALE_DELETE,
    PERMISSION.TRANSACTION_DAMAGE_VIEW,
    PERMISSION.TRANSACTION_DAMAGE_CREATE,
    PERMISSION.TRANSACTION_DAMAGE_UPDATE,
    PERMISSION.TRANSACTION_DAMAGE_DELETE,
    PERMISSION.TRANSACTION_STOCK_ADJUSTMENT_VIEW,
    PERMISSION.TRANSACTION_STOCK_ADJUSTMENT_CREATE,
    PERMISSION.TRANSACTION_STOCK_ADJUSTMENT_UPDATE,
    PERMISSION.TRANSACTION_STOCK_ADJUSTMENT_DELETE,
    PERMISSION.TRANSACTION_TRANSFER_IN_VIEW,
    PERMISSION.TRANSACTION_TRANSFER_IN_CREATE,
    PERMISSION.TRANSACTION_TRANSFER_IN_UPDATE,
    PERMISSION.TRANSACTION_TRANSFER_IN_DELETE,
    PERMISSION.TRANSACTION_TRANSFER_OUT_VIEW,
    PERMISSION.TRANSACTION_TRANSFER_OUT_CREATE,
    PERMISSION.TRANSACTION_TRANSFER_OUT_UPDATE,
    PERMISSION.TRANSACTION_TRANSFER_OUT_DELETE,
    PERMISSION.TRANSACTION_RETURN_SALE_VIEW,
    PERMISSION.TRANSACTION_RETURN_SALE_CREATE,
    PERMISSION.TRANSACTION_RETURN_SALE_UPDATE,
    PERMISSION.TRANSACTION_RETURN_SALE_DELETE,
    PERMISSION.TRANSACTION_RETURN_PURCHASE_VIEW,
    PERMISSION.TRANSACTION_RETURN_PURCHASE_CREATE,
    PERMISSION.TRANSACTION_RETURN_PURCHASE_UPDATE,
    PERMISSION.TRANSACTION_RETURN_PURCHASE_DELETE,
    PERMISSION.TRANSACTION_PRODUCTION_INPUT_VIEW,
    PERMISSION.TRANSACTION_PRODUCTION_INPUT_CREATE,
    PERMISSION.TRANSACTION_PRODUCTION_INPUT_UPDATE,
    PERMISSION.TRANSACTION_PRODUCTION_INPUT_DELETE,
    PERMISSION.TRANSACTION_PRODUCTION_OUTPUT_VIEW,
    PERMISSION.TRANSACTION_PRODUCTION_OUTPUT_CREATE,
    PERMISSION.TRANSACTION_PRODUCTION_OUTPUT_UPDATE,
    PERMISSION.TRANSACTION_PRODUCTION_OUTPUT_DELETE,
  ],
  CUSTOMERS: [
    PERMISSION.CUSTOMER_VIEW,
    PERMISSION.CUSTOMER_CREATE,
    PERMISSION.CUSTOMER_UPDATE,
    PERMISSION.CUSTOMER_DELETE,
  ],
  FINANCIAL: [
    PERMISSION.FINANCIAL_VIEW,
    PERMISSION.FINANCIAL_REPORTS,
    PERMISSION.FINANCIAL_EXPORT,
  ],
  SYSTEM: [
    PERMISSION.SYSTEM_SETTINGS,
    PERMISSION.SYSTEM_BACKUP,
    PERMISSION.SYSTEM_LOGS,
    PERMISSION.SYSTEM_MAINTENANCE,
  ],
  AUDIT: [PERMISSION.AUDIT_VIEW, PERMISSION.AUDIT_EXPORT],
} as const;
